version: '3.7'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: budget_db
      MYSQL_ROOT_PASSWORD: rootp

  app:
    build: .
    working_dir: /var/www/html
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - "81:80"
    depends_on:
      - db